agents:
  queue: hosted

env:
  MISE_YES: "1"
  MISE_TRUSTED_CONFIG_PATHS: /buildkite/builds

steps:
  - label: ":typescript: Typecheck"
    command: mise exec node -- pnpm install && mise exec node -- pnpm typecheck

  - label: ":test_tube: Test"
    command: mise exec node -- pnpm install && mise exec node -- pnpm test

  - label: ":package: Build"
    command: mise exec node -- pnpm install && mise exec node -- pnpm build

  - wait

  - block: ":rocket: Deploy to Staging"
    if: build.pull_request.id != null

  - label: ":fly: Deploy Staging"
    if: build.pull_request.id != null
    command: mise exec -- flyctl deploy --config fly.staging.toml --remote-only
    secrets:
      - FLY_API_TOKEN_STAGING

  - wait

  - label: ":fly: Deploy Production"
    branches: main
    command: mise exec -- flyctl deploy --config fly.toml --remote-only
    secrets:
      - FLY_API_TOKEN_PRODUCTION
